### ISSUE TITLE
Cannot spawn rtl_433

### ISSUE THREAD

**Issue by tastycorn** [NorthernMan54/homebridge-rtl#2]
Any idea why when starting HomeBridge, the plugin is unable to spawn an instance of rtl_433?

![image](https://user-images.githubusercontent.com/23389178/93651408-9c5ad880-f9ce-11ea-9fc7-eb80d6c5af91.png)

**Comment by tastycorn** [comment]
Nevermind. It is a permissions thing. I installed HomeBridge after installing rtl-sdr, so the homebridge user did not have access to the SDR dongle.

**Comment by stefanolarentis** [comment]
I have the exact same issue. Can you describe how you resolved it?

**Comment by NorthernMan54** [comment]
Add the homebridge account to the 'plugdev' group
